package entities;

public class AfterSaleInfo {

    int driver_id = 0; //7659
    int product_id = 0; //69909
    int shipping_line_id = 0; //267
    int station_id = 0; //9
    int entity_id = 0; //71987
    int order_item_id = 0; //11876200
    int specification_id = 0; //116061
    int order_id = 0; //10003575
    int website_id = 0; //3
    int store_id = 0; //2716
    int customer_id = 0; //258740
    int level_2_value = 0; //0
    int level_3_value = 0; //
    int level_type = 0; //1
    int pick_user_type = 0; //2
    int problem_type = 0; //6
    int apply_type = 0; //2
    int after_process_type = 0; //1
    int province = 0; //13
    int status = 0; //3
    int city = 0; //193
    int isC = 0; //0

    float original_price = 0.0f; //40
    float discount_price = 0.0f; //40
    float shop_coupon_amount = 0.0f; //0
    float price = 0.0f; //40
    float original_amount = 0.0f; //1
    float discount_avg_price = 0.0f; //40
    float avg_price = 0.0f; //40
    float discount_total_price = 0.0f; //40
    float original_total_price = 0.0f; //40
    float coupon_amount = 0.0f; //0
    float amount = 0.0f; //1
    float total_price = 0.0f; //40
    float pay_amount = 0.0f; //0
    float commission = 0.0f; //0.8

    String driver_remark = ""; //
    String customer_tel = ""; //13995566720
    String qr_code_id = ""; //9210308000027
    String addition_remark = ""; //
    String sku = ""; //
    String problemDes = ""; //发错货
    String station_name = ""; //武泰闸配送中心
    String problem_description = ""; //把
    String shipping_line_code = ""; //1004-7
    String customer_address = ""; //汇通新长江中心B座1102室
    String dispatch_time = ""; //2021-03-08 10:05
    String create_time = ""; //2021-03-08 10:04
    String streetNumber = ""; //测试
    String product_criteria = ""; //1
    String operator_account = ""; //13995567535
    String hotel_name = ""; //测试门店720
    String operator_user_name = ""; //吴玲
    String order_pay_time = ""; //2021-03-08 09:57
    String unit = ""; //斤
    String out_trade_no = ""; //0003_KQwA3DZcRa20210308095750749
    String level_2_unit = ""; //
    String nick_name = ""; //
    String supplier_tel = ""; //12345678009
    String name = ""; //土鸡蛋
    String pick_user_phone = ""; //12345678106
    String order_no = ""; //67745084142037934084
    String commissionerName = ""; //101
    String receive_user_name = ""; //企业720
    String receive_user_tel = ""; //13995566720
    String level_3_unit = ""; //
    String receive_hotel_name = ""; //测试门店720
    String after_sales_no = ""; //1615169084894
    String city_name = ""; //武汉
    String store_name = ""; //测试环境店铺
    String submitter_name = ""; //测试门店720
    String supplier_name = ""; //测试WL
    String receive_address = ""; //_汇通新长江中心B座1102室(测试)
    String commissionerPhone = ""; //13995566101
    String create_order_time = ""; //2021-03-08 09:57
    String required_delivery_time = ""; //2021-03-08 08:00
    String pick_user_name = ""; //张家虎
    String submitter_tel = ""; //13995566720
    String avg_unit = ""; //斤
    String commissioner_name = ""; //吴玲
    String customer_name = ""; //企业720
    String certificate_photos = ""; //http://tsp-img.oss-cn-hangzhou.aliyuncs.com/2103081004424009e21f.jpg
    String store_img = ""; //http://tsp-img.oss-cn-hangzhou.aliyuncs.com/201116151846db9ccb9b.jpg
    String customer_img = ""; //http://tsp-img.oss-cn-hangzhou.aliyuncs.com/2008141407060fb47167.jpg
    String product_img = ""; //http://tsp-img.oss-cn-hangzhou.aliyuncs.com/201120151850ddb36961.jpg


    @Override
    public String toString() {
        return "AfterSaleInfo{" +
                "driver_id=" + driver_id +
                ", product_id=" + product_id +
                ", shipping_line_id=" + shipping_line_id +
                ", station_id=" + station_id +
                ", entity_id=" + entity_id +
                ", order_item_id=" + order_item_id +
                ", specification_id=" + specification_id +
                ", order_id=" + order_id +
                ", website_id=" + website_id +
                ", store_id=" + store_id +
                ", customer_id=" + customer_id +
                ", level_2_value=" + level_2_value +
                ", level_3_value=" + level_3_value +
                ", level_type=" + level_type +
                ", pick_user_type=" + pick_user_type +
                ", problem_type=" + problem_type +
                ", apply_type=" + apply_type +
                ", after_process_type=" + after_process_type +
                ", province=" + province +
                ", status=" + status +
                ", city=" + city +
                ", isC=" + isC +
                ", original_price=" + original_price +
                ", discount_price=" + discount_price +
                ", shop_coupon_amount=" + shop_coupon_amount +
                ", price=" + price +
                ", original_amount=" + original_amount +
                ", discount_avg_price=" + discount_avg_price +
                ", avg_price=" + avg_price +
                ", discount_total_price=" + discount_total_price +
                ", original_total_price=" + original_total_price +
                ", coupon_amount=" + coupon_amount +
                ", amount=" + amount +
                ", total_price=" + total_price +
                ", pay_amount=" + pay_amount +
                ", commission=" + commission +
                ", driver_remark='" + driver_remark + '\'' +
                ", customer_tel='" + customer_tel + '\'' +
                ", qr_code_id='" + qr_code_id + '\'' +
                ", addition_remark='" + addition_remark + '\'' +
                ", sku='" + sku + '\'' +
                ", problemDes='" + problemDes + '\'' +
                ", station_name='" + station_name + '\'' +
                ", problem_description='" + problem_description + '\'' +
                ", shipping_line_code='" + shipping_line_code + '\'' +
                ", customer_address='" + customer_address + '\'' +
                ", dispatch_time='" + dispatch_time + '\'' +
                ", create_time='" + create_time + '\'' +
                ", streetNumber='" + streetNumber + '\'' +
                ", product_criteria='" + product_criteria + '\'' +
                ", operator_account='" + operator_account + '\'' +
                ", hotel_name='" + hotel_name + '\'' +
                ", operator_user_name='" + operator_user_name + '\'' +
                ", order_pay_time='" + order_pay_time + '\'' +
                ", unit='" + unit + '\'' +
                ", out_trade_no='" + out_trade_no + '\'' +
                ", level_2_unit='" + level_2_unit + '\'' +
                ", nick_name='" + nick_name + '\'' +
                ", supplier_tel='" + supplier_tel + '\'' +
                ", name='" + name + '\'' +
                ", pick_user_phone='" + pick_user_phone + '\'' +
                ", order_no='" + order_no + '\'' +
                ", commissionerName='" + commissionerName + '\'' +
                ", receive_user_name='" + receive_user_name + '\'' +
                ", receive_user_tel='" + receive_user_tel + '\'' +
                ", level_3_unit='" + level_3_unit + '\'' +
                ", receive_hotel_name='" + receive_hotel_name + '\'' +
                ", after_sales_no='" + after_sales_no + '\'' +
                ", city_name='" + city_name + '\'' +
                ", store_name='" + store_name + '\'' +
                ", submitter_name='" + submitter_name + '\'' +
                ", supplier_name='" + supplier_name + '\'' +
                ", receive_address='" + receive_address + '\'' +
                ", commissionerPhone='" + commissionerPhone + '\'' +
                ", create_order_time='" + create_order_time + '\'' +
                ", required_delivery_time='" + required_delivery_time + '\'' +
                ", pick_user_name='" + pick_user_name + '\'' +
                ", submitter_tel='" + submitter_tel + '\'' +
                ", avg_unit='" + avg_unit + '\'' +
                ", commissioner_name='" + commissioner_name + '\'' +
                ", customer_name='" + customer_name + '\'' +
                ", certificate_photos='" + certificate_photos + '\'' +
                ", store_img='" + store_img + '\'' +
                ", customer_img='" + customer_img + '\'' +
                ", product_img='" + product_img + '\'' +
                '}';
    }
}
